name: Cypress Tests

on: 
  push:
    branches: ["master", "workflow"]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm i
      - name: build scss
        run: npm run build
      - name: build webpack
        run: npm run buildApp
      - name : run jest
        run: npm run test
      - name: Run cypress
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          spec: cypress/e2e
